---
query_string: |
  query {
    device(id: "{{ id}}") {
      hostname: name
      config_context
      bgp_routing_instances {
      extra_attributes
      autonomous_system {
        asn
      }
      address_families {
        afi_safi
        extra_attributes
      }
      peer_groups {
        name
        source_interface {
          name
        }
        extra_attributes
        secret {
          name
        }
        peergroup_template {
          autonomous_system {
            asn
          }
          extra_attributes
        }
        address_families {
          afi_safi
          import_policy
          export_policy
        }
      }
      endpoints {
        peer_group {
          name
        }
        source_ip {
          address
        }
        source_interface {
            name
          }
        peer {
          description          
          source_ip {
            address
          }
          address_families {
            afi_safi
            import_policy
            export_policy
          }
          autonomous_system {
            asn
          }
          routing_instance {
            autonomous_system {
              asn
            }
          }
        }
      }
    }
      position
      serial
      role {
        name
      }
      primary_ip4 {
        id
        primary_ip4_for {
          id
          name
        }
      }
      tenant {
        name
      }
      tags {
        name
      }
      role {
        name
      }
      platform {
        name
        network_driver
        manufacturer {
          name
        }
        network_driver
        napalm_driver
      }
      location {
        name
        vlans {
          name
          vid
        }
        parent {
          name
          vlans {
          name
          vid
        }
        }
      }
      interfaces {
        name
        description
        mac_address
        enabled
        mgmt_only
        label
        lag {
          name
        }
        cf_ospf_network_type
        cf_ospf_area
        cf_mpls_enabled
        ip_addresses {
          address
          tags {
            id
          }
        }
        mode
        tagged_vlans {
          id
        }
        untagged_vlan {
          id
        }
        connected_interface {
          name
          device {
            name
          }
        }
        tags {
          id
        }
      }
    }
  }