---
query_string: |
  query {
    device(id: "{{ id}}") {
      hostname: name
      config_context
      bgp_routing_instances{
        autonomous_system {
          asn
        }
        address_families {
          afi_safi
          extra_attributes
        }
        endpoints {
          peer {
            autonomous_system {
              asn
            }
            description
            source_ip {
              address
            }
            address_families {
              afi_safi
              import_policy
              export_policy
              multipath
              extra_attributes
            }
          }
        }
      }
      position
      serial
      role {
        name
      }
      primary_ip4 {
        id
        primary_ip4_for {
          id
          name
        }
      }
      tenant {
        name
      }
      tags {
        name
      }
      role {
        name
      }
      platform {
        name
        network_driver
        manufacturer {
          name
        }
        network_driver
        napalm_driver
      }
      location {
        name
        parent {
          name
        }
      }
      interfaces {
        description
        mac_address
        enabled
        mgmt_only
        cf_ospf_network_type
        cf_ospf_area
        cf_mpls_enabled
        name
        ip_addresses {
          address
          tags {
            id
          }
        }
        tagged_vlans {
          id
        }
        untagged_vlan {
          id
        }
        connected_interface {
          name
          device {
            name
          }
        }
        tags {
          id
        }
      }
    }
  }