---
query_string: |
  query {
    device(id: "{{ id}}") {
      config_context
      hostname: name
      position
      serial
      role {
        name
      }
      primary_ip4 {
        address
      }
      tenant {
        name
      }
      role {
        name
      }
      platform {
        name
        network_driver
        manufacturer {
          name
        }
        network_driver
        napalm_driver
      }
      location {
        name
        parent {
          name
        }
      }
      interfaces {
        description
        mac_address
        enabled
        mgmt_only
        cf_ospf_network_type
        cf_ospf_area
        cf_mpls_enabled
        name
        ip_addresses {
          address
        }
        tagged_vlans {
          id
        }
        untagged_vlan {
          id
        }
        connected_interface {
          name
          device {
            name
          }
        }
      }
    }
  }