---
query_string: |
  query {
    device(id: "{{ id}}") {
      hostname: name
      config_context
      bgp_routing_instances {
      extra_attributes
      autonomous_system {
        asn
      }
      address_families {
        afi_safi
        extra_attributes
      }
      peer_groups {
        name
        source_interface {
          name
        }
        autonomous_system {
          asn
        }
        extra_attributes
        secret {
          name
        }
        address_families{
          import_policy
          export_policy
          extra_attributes
        }
        peergroup_template {
          autonomous_system {
            asn
          }
          extra_attributes
        }
        address_families {
          afi_safi
          import_policy
          export_policy
        }
      }
      endpoints {
        peer_group {
          name
        }
        source_ip {
          address
        }
        source_interface {
            name
          }
        description
        peer {
          description          
          source_ip {
            address
          }
          address_families {
            afi_safi
            import_policy
            export_policy
          }
          autonomous_system {
            asn
          }
          routing_instance {
            autonomous_system {
              asn
            }
          }
        }
      }
    }
      position
      serial
      role {
        name
      }
      primary_ip4 {
        id
        primary_ip4_for {
          id
          name
        }
      }
      tenant {
        name
      }
      tags {
        name
      }
      role {
        name
      }
      platform {
        name
        network_driver
        manufacturer {
          name
        }
        network_driver
        napalm_driver
      }
      location {
        name
        vlans {
          name
          vid
          vlan_group {
            name
          }
        }
        parent {
          name
          vlans {
          name
          vid
          vlan_group {
            name
          }
        }
        }
      }
      interfaces {
        name
        description
        mac_address
        enabled
        mgmt_only
        label
        lag {
          name
        }
        cf_ospf_network_type
        cf_ospf_area
        cf_mpls_enabled
        cf_vrrp_group_id
        cf_vrrp_ipv4_enabled
        cf_vrrp_ipv6_enabled
        cf_vrrp_disabled
        cf_vrrp_preempt
        cf_vrrp_priority_level
        cf_vrrp_advertisement_interval
        cf_vrrp_bfd_enabled
        cf_vrrp_mac_advertisement_interval
        cf_vrrp_peer_address
        cf_vrrp_session_name
        cf_vrrp_timer_interval
        cf_vrrp_tracked_object
        ip_addresses {
          address
          tags {
            id
          }
        }
        mode
        tagged_vlans {
          vid
        }
        untagged_vlan {
          vid
        }
        connected_interface {
          name
          device {
            name
          }
        }
        cf_mlag_interface
        tags {
          id
        }
      }
    }
  }