---
- name: Pull Data from Nautobot
  delegate_to: localhost
  run_once: false
  networktocode.nautobot.query_graphql:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: false
    query: "{{ query_string }}"
    update_hostvars: true
    
- name: Flatten device data into top-level hostvars
  set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ hostvars[inventory_hostname].device | dict2items }}"
  when: hostvars[inventory_hostname].device is defined

- name: Ensure configs directory exists
  ansible.builtin.file:
    path: ./configs
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Template the router configurations
  ansible.builtin.template:
    src: "{{ ansible_network_os }}.j2"
    dest: "./configs/{{ inventory_hostname }}.conf"
  delegate_to: localhost