query_string: |
  {
    devices(name: "{{ item.0.device }}") {
      interfaces {
        name
        id
        ip_addresses {
          address
          id
        }
        connected_interface {
          name
          id
          ip_addresses {
            address
            id
          }
        }
      }
      bgp_routing_instances {
        id
        autonomous_system {
          id
        }
      }
    }
    ip_addresses(address: "{{ item.1.peer_address }}") {
      id
      interface_assignments {
        interface {
          name
          id
          device {
            name
            bgp_routing_instances {
              id
              autonomous_system {
                id
              }
            }
          }
        }
      }
    }
    autonomous_systems(asn: {{ item.1.peer_asn | int }}) {
      id
    }
    statuses(name: "Active") {
      id
    }
  }
