---
- name: Generate full Cisco lab configurations and deploy configurations
  hosts: ios
  gather_facts: false
  connection: network_cli
  vars_files:
    - vault.yml

  tasks:
    - name: Build Router Configurations 
      import_role: 
        name: build_lab_config
      tags: build
    
    - name: Deploy Router Configurations
      import_role: 
        name: deploy_lab_configs
      tags: deploy