---
- name: Populate Nautobot, Generate Containerlab topology from Nautobot, and generate full lab configurations and deploy them
  hosts: localhost
  gather_facts: false

  roles:
    - load_nautobot
    - build_clab_topology