---
- name: Generate full lab configurations and deploy
  hosts: ios
  gather_facts: false
  connection: network_cli
  vars_files:
    - vault.yml

  roles:
    - build_lab_config
    - deploy_lab_configs