- name: Generate AVD fabric config from Nautobot
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yml
  vars:
    group_vars_dir: "inventory/group_vars"
    spine_type: "spine"
    l3leaf_type: "l3leaf"
    l2leaf_type: "l2leaf"
  
  tasks:  
    - name: Build AVD topology file
      import_role:
        name: build_avd_fabric
      tags: build_avd_fabric