---
- name: Populate Nautobot, Generate Containerlab topology from Nautobot, and generate full lab configurations and deploy them
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - nautobot-data/extensible_data.yml
  - nautobot-data/origanization_data.yml
  - nautobot-data/ipam_data.yml
  - nautobot-data/nautobot_devices.yml

  roles:
    - load_nautobot
    - build_clab_topology


- name: Generate full Cisco & Arista lab configurations and deploy configurations
  hosts: all
  gather_facts: false
  connection: network_cli
  vars_files:
    - vault.yml

  tasks:
    - name: Build Router Configurations 
      import_role: 
        name: build_lab_config
      tags: build
    
    - name: Deploy Router Configurations
      import_role: 
        name: deploy_lab_configs
      tags: deploy