---
- name: Get data from Nautobot
  networktocode.nautobot.query_graphql:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    validate_certs: false
    query: |
      {
        devices  {
          name
          device_type{
            model
            manufacturer {
            name
          }
            }
          platform {
            name
          }
          software_version {
            version
          }
          interfaces {
            name
            mgmt_only
            ip_addresses {
              address
            }
            connected_interface {
              name
              device {
                name
              }
            }
          }
        }
      }
  register: "nb_devices"

- name: Create initial Configs for each device
  template:
    src: "initial_configs.j2"
    dest: "~/Nautobot-Workshop/clabs/startup-configs/{{ item.name }}.txt.partial"
  loop: "{{ nb_devices.data.devices }}"

- name: Render Containerlab topology
  template:
    src: "containerlab_topology.j2"
    dest: "~/Nautobot-Workshop/clabs/containerlab-topology.yml"