ansible_user: "{{ router_username }}"
ansible_password: "{{ router_password }}"
ansible_connection: ansible.netcommon.network_cli
ansible_become: true
ansible_become_method: enable
ansible_ssh_common_args: "-o PubkeyAuthentication=no -o PreferredAuthentications=password,keyboard-interactive -o StrictHostKeyChecking=no -o KexAlgorithms=+diffie-hellman-group14-sha1 -o HostKeyAlgorithms=+ssh-rsa"